# Generated by Django 4.1.3 on 2022-11-19 22:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('date', models.DateField(default=datetime.date)),
                ('photo', models.ImageField(upload_to='photo/awards')),
            ],
            options={
                'db_table': 'Awards',
            },
        ),
        migrations.CreateModel(
            name='licenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('link', models.ImageField(upload_to='photo/licenses')),
            ],
            options={
                'db_table': 'license',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalAccomplishement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ListOfAccomlishement', models.CharField(default='', max_length=70)),
                ('Example', models.CharField(default='', max_length=70)),
                ('photos', models.ImageField(upload_to='photo/ProfessionalAccomplishement')),
            ],
            options={
                'db_table': 'ProfessionalAccomplishement',
            },
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('job', models.CharField(default='', max_length=70)),
                ('Email', models.EmailField(default='my.mail@gmail.com', max_length=100)),
                ('phoneNumber', models.IntegerField(max_length=8)),
            ],
            options={
                'db_table': 'references',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=70)),
                ('FamilyName', models.CharField(default='', max_length=70)),
                ('birthday', models.DateField(default=datetime.date)),
                ('Email', models.EmailField(default='my.mail@gmail.com', max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('phoneNumber', models.IntegerField(max_length=8)),
                ('Photo', models.ImageField(upload_to='photo/user')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Volunteering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'Volunteering',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CareerSummary', models.CharField(default='', max_length=70)),
                ('PhilosophyStatement', models.CharField(default='', max_length=70)),
                ('Biography', models.CharField(default='', max_length=70)),
                ('accomplishement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.professionalaccomplishement')),
                ('awards', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.awards')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.licenses')),
                ('references', models.ManyToManyField(to='portfolio_app.references')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.user')),
                ('volunteering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.volunteering')),
            ],
            options={
                'db_table': 'Portfolio',
            },
        ),
    ]
