# Generated by Django 4.1.3 on 2022-11-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_biography_delete_adress_remove_portfolio_biography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='references',
            name='phoneNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.IntegerField(),
        ),
    ]
