# Generated by Django 4.1.3 on 2022-11-20 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_alter_references_phonenumber_alter_user_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='email',
            field=models.EmailField(blank=True, default='my.mail@gmail.com', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='biography',
            name='socialProfile',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='biography',
            name='website',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='biography',
            field=models.ForeignKey(max_length=70, on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.biography'),
        ),
        migrations.AlterField(
            model_name='references',
            name='phoneNumber',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterModelTable(
            name='references',
            table='references',
        ),
    ]
