# Generated by Django 4.1.3 on 2022-11-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_alter_biography_email_alter_biography_socialprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='title',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='licenses',
            name='title',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='professionalaccomplishement',
            name='Example',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='professionalaccomplishement',
            name='ListOfAccomlishement',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='volunteering',
            name='title',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
    ]
