# Generated by Django 4.1.3 on 2022-11-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_alter_awards_title_alter_licenses_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='CareerSummary',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='PhilosophyStatement',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='references',
            name='Email',
            field=models.EmailField(blank=True, default='my.mail@gmail.com', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='references',
            name='job',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='references',
            name='name',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='references',
            name='phoneNumber',
            field=models.IntegerField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='volunteering',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
